### ISSUE TITLE
Upgrade to React 18

### ISSUE THREAD

**Issue by ExtraBB** [OfficeDev/Office-Addin-TaskPane-React#115]
It would be nice to get an upgrade to React 18. `react-hot-loader` would no longer be needed there.

**Comment by peterddod** [comment]
If this is possible it would be great. There are some packages that are React 18+ only which would be nice to use alongside the Office JS/TS API. I've tried to do this manually but come across different issues. Is there an approach to this which makes it possible?

**Comment by millerds** [comment]
If you look at the linked PR for updating to React 18 we're caught between moving forward with the react version and having the template support older IE based webviews still in use in Office 2016.  As is, the template will support Office 2016, but that doesn't stop anyone from making a project from the template, updating the dependency to react 18 (and the fluent UI dependency), and making an add-in that isn't supported in older version of Office (you'll need a down level experience tell customer to upgrade office if you want to submit you add-in to the store).

**Comment by Rick-Kirkham** [comment]
This is being tracked in an internal bug, so I'm closing this.
