### ISSUE TITLE
Add-in only works when I click on "new email"

### ISSUE THREAD

**Issue by JokerMarwan** [OfficeDev/Office-Addin-TaskPane-React#134]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 930ce4fc-c8b8-f756-f03f-a716f1ef7883
* Version Independent ID: 753a2e38-9430-25bb-5409-b7eed9c88e47
* Content: [Build your first Outlook add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/outlook-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/outlook-quickstart.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
@JokerMarwan The command line error was a bug introduced last week in one of the tools that gets installed with a Yo Office project. It has now been fixed. If I reinstall Yo Office, I can no longer reproduce it.

**Comment by millerds** [comment]
Actually . . . looks like a bug in the newest version of 'winreg' which is a nested decency of the tools used in these projects.  It's still there.  I will be updating our tool to use a specific version of winreg that still works.  Thanks for point this out.
