### ISSUE TITLE
Hot reload seems to be not working

### ISSUE THREAD

**Issue by yamapi-t** [OfficeDev/Office-Addin-TaskPane-React#155]
# Expected behavior

Hot reload working correctly.
If I change and save some files, then I want the UI to change automatically.

# Current behavior

After executing the generator command `yo office`, hot reload is not working.
If I refresh the page manually, it will be updated.

## Steps to Reproduce

1. `npm install -g yo generator-office`
2. `yo office` and choose  react and typescript
3. `npm i && npm run dev-server`
4. change and save some files

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: mac 13.4.1
* Node version: v20.9.0
* Office version: 16.84

**Comment by Rick-Kirkham** [comment]
See [158](https://github.com/OfficeDev/Office-Addin-TaskPane-React/issues/158)
