### ISSUE TITLE
Body doesn't have ms-Fabric style

### ISSUE THREAD

**Issue by rob-deutsch** [OfficeDev/Office-Addin-TaskPane-React#23]
I loaded this addin to Excel, and I noticed that the style doesn't look right. In particular, the standard browser font is being used. I expected it to use Segoe UI Web.

I noticed that [Office-Addin-TaskPane/src/taskpane/taskpane.html#L23](https://github.com/OfficeDev/Office-Addin-TaskPane/blob/463fcd847321faf54581b844375ff4a3161a116a/src/taskpane/taskpane.html#L23) applies the ms-Fabric style to `body` which specifies the Segoe UI Web font family.

Does Office-Addin-TaskPane-React intentionally not use Segoe UI Web nor ms-Fabric?

**Comment by akrantz** [comment]
Thanks for raising this issue. If you can tell what changes are required, we welcome pull requests.
