### ISSUE TITLE
unused extra webpack config file created

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/Office-Addin-TaskPane-React#40]
When I create a yo office project with the React option, a config folder with webpack config files is created. These are called in the package.json as expected:
```
 "scripts": {
        "clean": "rimraf dist && rimraf .awcache",
        "lint": "tslint --project tsconfig.json",
        "start": "webpack-dev-server --inline --mode development --config config/webpack.dev.js --progress",
        "sideload": "office-toolbox sideload -m manifest.xml -a Excel",
        "build": "npm run clean && webpack --mode production --config config/webpack.prod.js --colors --progress --bail",
        "validate": "office-toolbox validate -m manifest.xml"
    },
```
But another webpack.config.js file is also created in the root of the project. It is never called by anything.

**Comment by akrantz** [comment]
@Rick-Kirkham Neither the "yo-office" or "master" branch contains a config directory any more. Did you get the latest version of generator-office using `npm install -g yo generator-office` before running `yo office`?

**Comment by akrantz** [comment]
I ran yo office to verify that there is no config folder generated. (I did React, TypeScript, Word.)
