### ISSUE TITLE
Webpack can't resolve "./src" in TS React project 

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/Office-Addin-TaskPane-React#41]
I installed latest Yo Office and created a project taking options React, TypeScript, and Excel.  Then I ran `npm install`. The Readme for office-generator doesn't indicate that anything further needs to be done before running scripts in the **package.json**. I ran `npm run build:dev` and got the following error. I get the identical error regardless of whether the command prompt is in the project root, where the **package.json** is or in the subfolder **Office-Addin-TaskPane-React-yo-office** where the **webpack.config.js** is. It seems like webpack is looking for `./src` under the project root instead of where it actually is in the **Office-Addin-TaskPane-React-yo-office** subfolder.

![image](https://user-images.githubusercontent.com/9088056/70872211-3d59c600-1f5b-11ea-8601-959b26cb4c91.png)

I get essentially the same error if I run `npm start`.

**Comment by TCourtneyOwen** [comment]
@Rick-Kirkham I was unable to repro this problem with the latest version of generator-office (1.4.0).  I even tried creating the same project folder (Office-Addin-TaskPane-React-yo-office) to ensure the problem isn't related to the folder name and didn't hit any issues. Can you please check the version you are running is the latest?

Thanks,

Courtney

**Comment by Rick-Kirkham** [comment]
@TCourtneyOwen The package.json file in C:\Users\Rick\AppData\Roaming\npm\node_modules\generator-office says it is version 1.4.0.

I'm puzzled when you say this: 
"I even tried creating the same project folder (Office-Addin-TaskPane-React-yo-office) to ensure the problem isn't related to the folder name and didn't hit any issues." 

I did not create that folder. It was created by the Yo Office tool. It is a subfolder of the folder with the project name that I chose "Another Office Add-in". Are you saying that the tool did not create that folder when you ran it?

**Comment by Rick-Kirkham** [comment]
@TCourtneyOwen I've run the tool several times now and it usually works. But there is an intermittent bug.  About 1/3 of the time that I run it, the project creation fails when trying to rename a folder named "Office-Addin-TaskPane-React-yo-office\scr" to "src". The error says:

`Error: EPERM: operation not permitted, rename 'D:\RNprojects\temp\Another Office Add-in\Office-Addin-TaskPane-React-yo-office\src' -> 'D:\RNprojects\temp\Another Office Add-in\src'`

As you can see in the screenshot below, I'm running in an elevated command prompt, so I have admin powers. 

The screenshot has the trace:
![image](https://user-images.githubusercontent.com/9088056/71036907-74eb7e00-20d3-11ea-828f-07c79ce5ce37.png)

**Comment by TCourtneyOwen** [comment]
I am betting this has to do with not running the command prompt as admin.  I saw similar behavior when I didn't run the command prompt as admin.  I will look into this and see if we can work around this

**Comment by Rick-Kirkham** [comment]
@TCourtneyOwen ??? But I am running it as an admin. See the title bar of the screenshot.

**Comment by LouMM** [comment]
@Rick-Kirkham Are you still seeing this issue. We don't have a repro of this issue, but if you are willing to sit with us, we can assist in debugging.
Cheers!
