### ISSUE TITLE
Q: Is it possible to include custom excel functions interacting with redux store ?

### ISSUE THREAD

**Issue by ThroughTheWind** [OfficeDev/Office-Addin-TaskPane-React#51]
Hello,

I'm currently working on an excel add-in in react using the dedicated yeoman generator for professional purposes.
My team and I were wondering if it was possible to integrate custom excel functions interacting with a redux store contained in the react taskpane ?
We've been struggling to find any documentation related to this question so any help would be gladly appreciated.

Thanks in advance.

**Comment by LouMM** [comment]
Currently, Custom Functions and Add-ins run on different runtimes (JavaScript vs Browser) Microsoft is working on a Shared runtime and we will have a template soon that maps to it. Once CF and Addins use the Shared runtime, they will be able to use the immutable redux store. Check out this sample we have in the meantime:
https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario
