### ISSUE TITLE
Not able to load addin in IE edge browser

### ISSUE THREAD

**Issue by AlavalaShreyas** [OfficeDev/Office-Addin-TaskPane-React#53]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [Yes ] I am running the latest version of Node and the tools 
- [Yes ] I checked the documentation and found no answer 
- [No ] I checked to make sure that this issue has not already been filed 

# Expected behavior

Please describe the behavior you were expecting

We have cloned from your repository and built our outlook addin, it works fine with Chrome, but it keeps on loading in IE edge browser. 
**Note** : we have not done any other changes on top of our code.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open Outlook in IE edge
2. Open Addin
3. It keeps on loading in IE edge.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* Node version: 14.4.0
* Office version: Beta
* Tool version :

## Failure Logs

* 0: SyntaxError 0.chunk.js (104601,1)
// Connect to WebpackDevServer via a socket.

 var connection = new WebSocket(

 url.format({

 protocol: 'ws',

 hostname: window.location.hostname,

 port: window.location.port,

 // Hardcoded in WebpackDevServer

 pathname: '/sockjs-node',

 })

 );
* Some times we get office.js is not initialized error.

**Comment by LouMM** [comment]
Thank you @AlavalaShreyas . Would you be able to share code with us that has this behavior? We are unable to get this to reproduce using our template.

**Comment by TCourtneyOwen** [comment]
There has been no follow-up communication from @AlavalaShreyas, so closing this. Please reactivate if you would like further investigation on this
