### ISSUE TITLE
Please provide a function component (hooks) version as well as the class-based approach

### ISSUE THREAD

**Issue by johnkazer** [OfficeDev/Office-Addin-TaskPane-React#72]
# Expected behavior

There should ideally be a parallel version based on function rather than class components. Or a link to instructions on how to make the conversion.

# Current behavior

I have to convert the examples to function components manually

## Steps to Reproduce

N/A

## Context

N/A

## Failure Logs

N/A

**Comment by millerds** [comment]
We aren't able to provide numerous variations of template for the variety of different features in the variety of different frameworks.  There seems to be a lot of general help on the web for converting from class-based components to functional-based components.

https://www.bing.com/search?q=react+convert+class+to+function
