### ISSUE TITLE
i want to open automatically this Add-in when open word document how i can ?

### ISSUE THREAD

**Issue by hammadshahid-170** [OfficeDev/Office-Addin-TaskPane-React#79]
i want to open automatically this Add-in when open word document how i can ? please give me solution @igor-ribeiiro

**Comment by igor-ribeiiro** [comment]
Hi @hammadshahid-170, I don't quite get what you mean on automatically load the add-in. It will open normally when running the project.
Please, see this tutorial: [Word addin quickstart](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator)
