### ISSUE TITLE
Event handlers only work if declared inline. Reference to this.myHandler is ignored

### ISSUE THREAD

**Issue by avalanche1** [OfficeDev/Office-Addin-TaskPane-React#8]
None of my `this.setState()` calls ever update component's state. 
## Expected Behavior

normal React behaviour
## Current Behavior

State updates just will not fire.
## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
Create a piece of state in the App component of default project. Try to change it via button click. The change never occurs.

## Context

I am trying to do some basic react rendering of the add-in panel components.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: macos mojave
* Host [Excel, Word, PowerPoint, etc.]: excel
* Office version number: 16.16.8

## Useful logs
```
export interface AppProps {
  title: string;
  isOfficeInitialized: boolean;
}

interface AppState {
  isMacroRunning: any;
}

export default class App extends React.Component<AppProps, AppState> {
  constructor(props, context) {
    super(props, context);
    this.state = {
      isMacroRunning: false,
    };
    this.run_macro = this.run_macro.bind(this);
  }

  run_macro = () => {
    this.setState({isMacroRunning: true});
    // Macro code here
    this.setState({isMacroRunning: false});
  }

  render() {
    const {title, isOfficeInitialized} = this.props;

    if (!isOfficeInitialized) {
      return (
        <Progress
          title={title}
          logo="assets/logo-filled.png"
          message="Please sideload your add-in to see app body."
        />
      );
    } else if (this.state.isMacroRunning) {
      return (
        <Progress
          title={title}
          logo="assets/logo-filled.png"
          message="Macro execution in progress.."
        />
      );
    } else {
      return (
        <div className="ms-welcome">
          <p>{JSON.stringify(this.state.isMacroRunning)}</p>
          {/*<Header title="Welcome" />*/}
          <Content
            // message=""
            buttonLabel="Collect data"
            click={this.run_macro}
          />
        </div>
      );
    }
  }
}

```

**Comment by TCourtneyOwen** [comment]
Are people actually using this repo already or is this an internal issue?

On Apr 5, 2019, at 2:01 PM, Adam Krantz <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #8<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2FOffice-Addin-TaskPane-React%2Fissues%2F8&data=02%7C01%7Ccowen%40microsoft.com%7C87ec1bd80d1f4fa9341e08d6ba09e218%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636900948943567550&sdata=yKSuiq5xOmNtqTbbtFKndXRZCqqibgEU%2BGWH7O2R%2Fy8%3D&reserved=0> to @TCourtneyOwen<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTCourtneyOwen&data=02%7C01%7Ccowen%40microsoft.com%7C87ec1bd80d1f4fa9341e08d6ba09e218%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636900948943577547&sdata=hYon8nKjL553JjkQPu0ebbDRF3o5dHLxiMRFwD3YljM%3D&reserved=0>.

**Comment by Rick-Kirkham** [comment]
@TCourtneyOwen This happens on projects created with yo office (React option). As I understand it, that's the same as starting a project by cloning this repo.

**Comment by TCourtneyOwen** [comment]
Not yet actually. We are still using the built in yo office templates and not pulling from the repos yet. That said, it’s likely an issue with both the built in yo office template and this repo as well

**Comment by Rick-Kirkham** [comment]
@TCourtneyOwen 
Do you want to keep the issue here or move it to the generator repo?

**Comment by TCourtneyOwen** [comment]
Let’s keep it here since we will start pulling from the repos in the very near future. Thanks!

**Comment by avalanche1** [comment]
@Rick-Kirkham , I think you renamed the issue incorrectly. Event handlers do work. But state is not being updated by `this.setState()` calls.

**Comment by Rick-Kirkham** [comment]
@avalanche1 
My experience is that even handlers that don't try to change state don't run if they are not defined inline. It was my understanding from what you said above --  "Yes it's working." after defining your state-changing handler in line -- that you _are_ getting state to change.

**Comment by avalanche1** [comment]
I am getting it to change when running inline, yes.
Also when calling a method, everything's working except this.setState() calls.

**Comment by TCourtneyOwen** [comment]
I was able to set the state and read the state with the following code, which only slightly modifies the React Template:

import * as React from 'react';
import { Button, ButtonType } from 'office-ui-fabric-react';
import Header from './Header';
import HeroList, { HeroListItem } from './HeroList';
import Progress from './Progress';

export interface AppProps {
  title: string;
}

export interface AppState {
  listItems: HeroListItem[];
  isMacroRunning: boolean;
}

export default class App extends React.Component<AppProps, AppState> {
  constructor(props, context) {
    super(props, context);
    this.state = {
      listItems: [],
      isMacroRunning: false
    };
    this.run_macro = this.run_macro.bind(this);
  }

  run_macro = () =>   {
    this.setState({ isMacroRunning: true });
  }

  componentDidMount() {
    this.setState({
      listItems: [
        {
          icon: 'Ribbon',
          primaryText: 'Achieve more with Office integration'
        },
        {
          icon: 'Unlock',
          primaryText: 'Unlock features and functionality'
        },
        {
          icon: 'Design',
          primaryText: 'Create and visualize like a pro'
        }
      ]
    });
  }

  click = async () => {
    try {
      await Excel.run(async context => {
        /**
         * Insert your Excel code here
         */
        const range = context.workbook.getSelectedRange();

        // Read the range address
        range.load("address");

        // Update the fill color
        range.format.fill.color = "yellow";

        await context.sync();
        console.log(`The range address was ${range.address}.`);
      });
    } catch (error) {
      console.error(error);
    }
  }

  render() {
    const {
      title,
    } = this.props;

    if (this.state.isMacroRunning) {
      return (
        <Progress
          title={title}
          logo='assets/logo-filled.png'
          message='Please sideload your addin to see app body!'
        />
      );
    }

    return (
      <div className='ms-welcome'>
        <Header logo='assets/logo-filled.png' title={this.props.title} message='Welcome' />
        <HeroList message='Discover what Office Add-ins can do for you today sucka!' items={this.state.listItems}>
          <p className='ms-font-l'>Modify the source files, then click <b>Run</b>.</p>
          <Button className='ms-welcome__action' buttonType={ButtonType.hero} iconProps={{ iconName: 'ChevronRight' }} onClick={this.run_macro}>Run</Button>
        </HeroList>
      </div>
    );
  }
}

**Comment by TCourtneyOwen** [comment]
@avalanche1 I am going to close this issue for now, as I was able to set and read the state as mentioned above. If you haven't already done so, please refer to the React documentation for how to use setState (https://css-tricks.com/understanding-react-setstate/)
